# Generated by Django 5.0.4 on 2024-04-05 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='lock',
        ),
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
    ]
