# Generated by Django 5.0.4 on 2024-04-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_card_lock_remove_card_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='card',
            name='due_date',
        ),
    ]
