# Generated by Django 5.0.4 on 2024-04-05 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_card_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lock',
            name='device',
        ),
    ]
