# Generated by Django 5.0.4 on 2024-04-05 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_lock_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='lock',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.device'),
        ),
    ]
