# Generated by Django 5.0.4 on 2024-04-05 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_lock_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='lock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.lock'),
        ),
    ]
